[package]
name = "fillme"
version = "0.1.0"
authors = ["briviere <briviere@student.42.fr>"]

[dependencies]
failure = "*"

[dependencies.sdl2]
git = "https://github.com/Rust-SDL2/rust-sdl2"
features = ["ttf"]
